# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug  2 09:28:21 2011

import wx
import sys
import os
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class RowConfigure(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RowConfigure.__init__
        if os.name == 'nt':
            kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.SYSTEM_MENU|wx.SIMPLE_BORDER|wx.FRAME_TOOL_WINDOW|wx.FRAME_NO_TASKBAR
        else:
            kwds["style"] = wx.MINIMIZE_BOX | wx.CLOSE_BOX

        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        
        # Menu Bar
        self.configuration_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.configuration_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.configuration_menubar)
        # Menu Bar end
        self.panel_1 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self, -1, "CrunchTime Rowathon Client")
        self.panel_2 = wx.Panel(self, -1)
        self.panel_3 = wx.Panel(self, -1)
        self.panel_4 = wx.Panel(self, -1)
        self.panel_5 = wx.Panel(self, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.panel_9 = wx.Panel(self, -1)
        self.panel_6 = wx.Panel(self, -1)
        self.panel_7 = wx.Panel(self, -1)
        self.panel_8 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.quit, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RowConfigure.__set_properties
        self.SetTitle("CrunchTime Rowathon Client")
        self.SetSize((639, 439))
        self.panel_1.SetMinSize((186,20))
        self.label_1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.panel_2.SetMinSize((20,20))
        self.panel_3.SetMinSize((213, 20))
        self.panel_4.SetMinSize((20,20))
        self.panel_5.SetMinSize((20, 66))
        self.notebook_1.SetMinSize((590, 300))
        self.panel_9.SetMinSize((20, 66))
        self.panel_6.SetMinSize((20,20))
        self.panel_7.SetMinSize((213, 20))
        self.panel_8.SetMinSize((20,20))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RowConfigure.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(3, 3, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_4, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_5, 1, wx.EXPAND, 0)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Run")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Configure")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "About")
        grid_sizer_2.Add(self.notebook_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_9, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_6, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_7, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_8, 1, wx.EXPAND, 0)
        sizer_1.Add(grid_sizer_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def quit(self, event): # wxGlade: RowConfigure.<event_handler>
        sys.exit(0)

# end of class RowConfigure


