# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Aug  2 09:28:21 2011

import wx
import sys
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class RowConfigure(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RowConfigure.__init__
        kwds["style"] = wx.CLOSE_BOX|wx.MINIMIZE_BOX
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Configure the CT Rowathon Client", style=wx.ALIGN_CENTRE)
        
        # Menu Bar
        self.configuration_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.configuration_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.configuration_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.quit, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RowConfigure.__set_properties
        self.SetTitle("Rowathon Configuration")
        self.SetSize((639, 439))
        self.label_1.SetMinSize((639, 29))
        self.label_1.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RowConfigure.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.label_1, 3, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def quit(self, event): # wxGlade: RowConfigure.<event_handler>
        sys.exit(0)

# end of class RowConfigure


